name: wall_dock
description: A new Flutter project.


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  flutter_staggered_grid_view:
  google_fonts:
  firebase_admob: ^0.9.0+10
  photo_view: ^0.9.1
  line_icons: ^0.2.0
  dots_indicator: ^1.1.0
  extended_image: ^0.7.1
  splashscreen:
  device_info: ^0.4.1+4
  image_picker_saver:
  rxdart: ^0.22.2
  provider:
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/wallLogo.png
    - assets/wall.gif
    - assets/animal.jpg
    - assets/background.jpg
    - assets/education.jpg
    - assets/fashion.jpg
    - assets/science.jpg
    - assets/nature.jpg
    - assets/buildings.jpg
    - assets/business.jpg
    - assets/computer.jpg
    - assets/factory.jpg
    - assets/feel.jpg
    - assets/food.jpg
    - assets/health.jpg
    - assets/music.jpg
    - assets/people.jpg
    - assets/regions.jpg
    - assets/sports.jpg
    - assets/transportation.jpg
    - assets/travel.jpg
    - assets/places.jpg
    - assets/wallpaper.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
